spring:
  config:
    activate:
      on-profile: dev

  swagger:
    id: ${SWAGGER_ID}
    password: ${SWAGGER_PASSWORD}

  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${DEV_REDIS_HOST}
      port: 6379

  jwt:
    secret: ${JWT_SECRET_KEY} # JWT 시크릿 키
    token:
      access-expiration-time: ${JWT_ACCESS_EXP}  # Access Token 만료 시간
      refresh-expiration-time: ${JWT_REFRESH_EXP}  #  Refresh Token 만료 시간

  cookie:
    secure: true  # 운영환경(HTTPS)에서는 true, 로컬 HTTP 테스트 시에는 false
    same-site: Lax

  security:
    naver:
      client:
        id: ${NAVER_CLIENT_ID}
        secret: ${NAVER_CLIENT_SECRET}

      authorization-uri: https://nid.naver.com/oauth2.0/authorize
      redirect-uri: http://localhost:8080/api/v1/auth/naver/callback
      token-uri: https://nid.naver.com/oauth2.0/token
      user-info-uri: https://openapi.naver.com/v1/nid/me